#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';
require __DIR__.'/src/WetWalk/Command/CreateDryRun.php';
require __DIR__.'/src/WetWalk/MakeDry.php';
require __DIR__.'/src/WetWalk/Parser.php';

use Symfony\Component\Console\Application;
use WetWalk\Command\CreateDryRun;

$application = new Application();

$application->add(new CreateDryRun());

$application->run();
